Repository gomate-community/TrustRAG, pull requests merged in 2024-11, with the labels that each got.

#77 Pipeline
  gomate/applications/rag.py
  gomate/modules/citation/source_citation.py
  gomate/modules/clusters/utils.py
  gomate/modules/document/json_parser.py
Labels: bug

#78 支持es、monngo以及minio
  api/apps/core/judge/bodys.py
  api/apps/core/judge/views.py
  api/apps/core/parser/views.py
  api/apps/core/rerank/views.py
  api/apps/core/rewrite/bodys.py
  api/apps/core/rewrite/models.py
  api/apps/core/rewrite/views.py
  api/main.py
  examples/judger/bgejudger_exmpale.py
  examples/judger/chatgpt_judger.py
  examples/judger/citation.json
  examples/rewriters/openai_rewriter_example.py
  gomate/modules/citation/citation_match.json
  gomate/modules/citation/citation_match_res.json
  gomate/modules/citation/match_citation.py
  gomate/modules/engine/__init__.py
  gomate/modules/engine/es.py
  gomate/modules/engine/minio.py
  gomate/modules/engine/mongo.py
  gomate/modules/judger/chatgpt_judger.py
  gomate/modules/rewriter/openai_rewrite.py
  requirements.txt
Labels: enhancement

#79 update readme
  README.md
  README_en.md
Labels: documentation
